services:

  backend-dev:
    container_name: backend-dev
    build:
      context: backend
      dockerfile: Dockerfile.dev
    env_file: .env.dev.example
    ports:
      - "4000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./backend/src:/app/src
    networks:
      - backend_network

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    env_file: .env.dev.example
    volumes:
      - postgres-data:/data/postgres
    networks:
      - backend_network

  frontend-dev:
    container_name: frontend-dev
    build: 
      context: frontend
      dockerfile: Dockerfile.dev
    env_file: .env.dev.example
    ports:
      - "8081:3000"
    restart: unless-stopped
    depends_on:
      - backend-dev
    volumes:
      - ./frontend/src:/app/src
    networks:
      - frontend_network

volumes:
  postgres-data:

networks:
  backend_network:
  frontend_network:
